### ISSUE TITLE
Feature Request: Add Entity "device_last_seen"

### ISSUE THREAD

**Issue by pos-ei-don** [mampfes/ha_freeair_connect#1]
Thank you a lot!!! for this addin! I really hoped that someone will add this!

I have two Devices which are powered off most of the time (guest room).
I'd like to see if the values i see in HA are current or old.
To i used in my old visualistion (fhem) this value to determine, if i should ignore the values of this device.

**Comment by mampfes** [comment]
Where do I find this timestamp (e.g. on the freeair-connect website)? Is is the following line from the "Minute Values" page?
![image](https://user-images.githubusercontent.com/375950/219942063-9465aac5-026d-48d4-92b2-b80f98b4ac0f.png)

**Comment by mampfes** [comment]
fixed with 1fb3f50

**Comment by mampfes** [comment]
Please check if release 1.1.0 fixed this issue. If not, reopen this issue.

**Comment by pos-ei-don** [comment]
Thank you a lot, I will test it next week when I am home again.

**Comment by pos-ei-don** [comment]
Works great, thank you
