### ISSUE TITLE
Steuerung nicht möglich

### ISSUE THREAD

**Issue by Flyer0** [mampfes/ha_freeair_connect#15]
Freeair Steuerelemente funktionieren nicht

**Comment by mampfes** [comment]
Please provide more information! E.g. HA revision, configuration, FreeAir version info, debug logs.

**Comment by Flyer0** [comment]
Hallo,

HA 13.1. SV 2024.08.0 Core 2024.9.1
Freeair 2.22, vorher 2.21
Ich betreibe 2 Freeair Geräte und habe eine Automation, mit der ich die Geräte am Morgen auf Turbo schalte, das funktioniert nicht mehr, auch die Schaltflächen der Integration funktionieren nicht mehr (Sie zeigen den jeweiligen Zustand der Geräte richtig an, aber man kann nicht mehr steuern.).

Grüße, Stefan



Von: Steffen Zimmermann ***@***.***>
Antworten an: mampfes/ha_freeair_connect ***@***.***>
Datum: Freitag, 6. September 2024 um 20:46
An: mampfes/ha_freeair_connect ***@***.***>
Cc: Flyer0 ***@***.***>, Author ***@***.***>
Betreff: Re: [mampfes/ha_freeair_connect] Steuerung nicht möglich (Issue #15)


Please provide more information! E.g. HA revision, configuration, FreeAir version info, debug logs.

**Comment by mampfes** [comment]
>Freeair 2.22, vorher 2.21

D.h. Du hast von 2.21 auf 2.22 aktualisiert und danach ging es nicht mehr?

**Comment by Flyer0** [comment]
Nein, es ging dann schon irgendwann mit 2.21 nicht mehr, 2.22 brachte keine Veränderung.

 

Von: Steffen Zimmermann ***@***.***>
Antworten an: mampfes/ha_freeair_connect ***@***.***>
Datum: Mittwoch, 11. September 2024 um 20:18
An: mampfes/ha_freeair_connect ***@***.***>
Cc: Flyer0 ***@***.***>, Author ***@***.***>
Betreff: Re: [mampfes/ha_freeair_connect] Steuerung nicht möglich (Issue #15)

 

Freeair 2.22, vorher 2.21

D.h. Du hast von 2.21 auf 2.22 aktualisiert und danach ging es nicht mehr?

**Comment by MCoLoL** [comment]
I also have the same problem, i can't change the operation mode.
The problem was present also with the version 1.4.2; i just updated to 1.4.3 but the problem is still present.
I have two freeAir 100 updated to v2.14
If i can help with logs or other stuff let me know
Thanks

**Comment by BenRomberg** [comment]
PR opened, you can also try to manually fix it by replacing `data` in `custom_components/freeair_connect/FreeAir/__init__.py` like this:
```
        data = {
            "RB_CL": comfort_level,
            "RB_OM": operation_mode,
            "srn_button": f"{self._serial_no}-Test",
            "lang_button": "en",
            "serial_password": "",
        }
```
