### ISSUE TITLE
Link zu Freeair-Connect funktioniert nicht

### ISSUE THREAD

**Issue by satchafunkilus** [mampfes/ha_freeair_connect#16]
Wenn man in HA in der Geräteübersicht auf "Besuchen" klickt, um auf die Website von freeair-connect zu kommen, verweist der Link auf die URL https://freeair-connect.de/tabs.php?sn=XXXXX. Dort erhält man eine Fehlermeldung, da /tabs.php nicht existiert. Die korrekte URL lautet https://freeair-connect.de/?lang=de&serialnumber=XXXXX

**Comment by mampfes** [comment]
fixed in release 1.4.3
