### ISSUE TITLE
absolute humidity

### ISSUE THREAD

**Issue by grericht** [mampfes/ha_freeair_connect#5]
In my web interface there is absolute humidity and not just relative. In this add on I only find the relative value. But it doesn't interest (me) that much. can you also get the absolute value in g/m³?

**Comment by mampfes** [comment]
If I remember correctly, the absolute humidity is not provided by the device itself, but calculated in the web frontend.
You can let HA calculate the absolute humidity, either via a template sensor or use an integration like this: https://github.com/dolezsa/thermal_comfort
